### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by Anderson-Juhasc** [blocktrail/simple-bitcoin-wallet-app#1]
How do I resolve this?

Problem 1
    - blocktrail/blocktrail-sdk v1.2.7 requires ext-intl \* -> the requested PHP extension intl is missing from your system.
    - blocktrail/blocktrail-sdk v1.2.6 requires ext-intl \* -> the requested PHP extension intl is missing from your system.
    - blocktrail/blocktrail-sdk v1.2.5 requires ext-intl \* -> the requested PHP extension intl is missing from your system.
    - blocktrail/blocktrail-sdk v1.2.4 requires ext-intl \* -> the requested PHP extension intl is missing from your system.
    - blocktrail/blocktrail-sdk v1.2.3 requires ext-intl \* -> the requested PHP extension intl is missing from your system.
    - blocktrail/blocktrail-sdk v1.2.2 requires ext-intl \* -> the requested PHP extension intl is missing from your system.
    - blocktrail/blocktrail-sdk v1.2.1 requires ext-intl \* -> the requested PHP extension intl is missing from your system.
    - blocktrail/blocktrail-sdk v1.2.0 requires ext-intl \* -> the requested PHP extension intl is missing from your system.
    - Installation request for blocktrail/blocktrail-sdk 1.2.\* -> satisfiable by blocktrail/blocktrail-sdk[v1.2.0, v1.2.1, v1.2.2, v1.2.3, v1.2.4, v1.2.5, v1.2.6, v1.2.7].

**Comment by rubensayshi** [comment]
you need to install the PHP INTL extension.

on ubuntu; `sudo apt-get install php5-intl`

if you're on another OS? let me know which one and I'll figure it out for you ;)

**Comment by Anderson-Juhasc** [comment]
I'm using Ubuntu.
The error persists.

Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - blocktrail/blocktrail-sdk v1.2.7 requires ext-gmp \* -> the requested PHP extension gmp is missing from your system.
    - blocktrail/blocktrail-sdk v1.2.6 requires ext-gmp \* -> the requested PHP extension gmp is missing from your system.
    - blocktrail/blocktrail-sdk v1.2.5 requires ext-gmp \* -> the requested PHP extension gmp is missing from your system.
    - blocktrail/blocktrail-sdk v1.2.4 requires ext-gmp \* -> the requested PHP extension gmp is missing from your system.
    - blocktrail/blocktrail-sdk v1.2.3 requires ext-gmp \* -> the requested PHP extension gmp is missing from your system.
    - blocktrail/blocktrail-sdk v1.2.2 requires ext-gmp \* -> the requested PHP extension gmp is missing from your system.
    - blocktrail/blocktrail-sdk v1.2.1 requires ext-gmp \* -> the requested PHP extension gmp is missing from your system.
    - blocktrail/blocktrail-sdk v1.2.0 requires ext-gmp \* -> the requested PHP extension gmp is missing from your system.
    - Installation request for blocktrail/blocktrail-sdk 1.2.\* -> satisfiable by blocktrail/blocktrail-sdk[v1.2.0, v1.2.1, v1.2.2, v1.2.3, v1.2.4, v1.2.5, v1.2.6, v1.2.7].

**Comment by rubensayshi** [comment]
Hey, you need a couple of packages actually;

```
$ sudo apt-get install php5-bcmath php5-intl php5-gmp php5-mcrypt
$ sudo php5enmod mcrypt
```

**Comment by Anderson-Juhasc** [comment]
return now:

{"error":{"type":"ErrorException","message":"Undefined index: APP_URL","file":"\/var\/www\/html\/simple-bitcoin-wallet-app\/app\/config\/app.php","line":29}}

**Comment by Anderson-Juhasc** [comment]
I change file .env.example.php to env.local.php

**Comment by rubensayshi** [comment]
that fixed it or still having the problem?

**Comment by rubensayshi** [comment]
try changing it to `env.php` instead of `env.local.php`

**Comment by bla-zurich** [comment]
And what about macOS Sierra?

$ php composer.phar install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - bitwasp/bitcoin-lib v1.0.6 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - bitwasp/bitcoin-lib v1.0.4 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - bitwasp/bitcoin-lib v1.0.2 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - Installation request for bitwasp/bitcoin-lib 1.0.* -> satisfiable by bitwasp/bitcoin-lib[v1.0.2, v1.0.4, v1.0.6].

**Comment by danersan** [comment]
@rubensayshi im using osx, any idea how to fix this? (i mean any command)
pretty new in this thing, so i dont hv any idea
thanks
